### ISSUE TITLE
Html

### ISSUE THREAD

**Issue by hs115488** [sajanshrestha/most_repeated_winning_numbers#1]
Why did you use xml to scrape the source code..... you could've used regular html.

**Comment by sajanshrestha** [comment]
‘lxml’ is parsing method for beautiful soup!

**Comment by hs115488** [comment]
Not true. You can use html. When you parse via html, you can call by id or by class to get the element value

**Comment by sajanshrestha** [comment]
You can do that with xml too..in fact i used class..

**Comment by hs115488** [comment]
You also have an unused library called "operator". That is just redundant from arithmetic expression. You can use a map function with lambda

**Comment by sajanshrestha** [comment]
This is not a perfect program! Im planning to make it better.. this is just
a first draft!
Operator
Is not unused!! Again, look closely 😂
